In [1]:
import numpy as np

x = np.matrix(
    "4,5,16,7;2,-3,2,3;3,4,5,6;4,7,8,9"
)

print(x)

[[ 4  5 16  7]
 [ 2 -3  2  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]


In [2]:
det_matrix = np.linalg.det(x)
print(det_matrix)

128.00000000000009
